/* eslint-disable */
// Generated by Wrangler by running `wrangler types backend/worker-configuration.d.ts --config backend/wrangler.production.json --env-interface ProductionEnv --include-runtime false --strict-vars false` (hash: 5656d00035fdf251decd450abbb9a8fe)
interface __BaseEnv_ProductionEnv {
	REVIEW_PHOTOS: R2Bucket;
	DB: D1Database;
	ALLOWED_ORIGINS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_ProductionEnv {}
}
interface ProductionEnv extends __BaseEnv_ProductionEnv {}
