export type LifePlace = { id: string; name: string; category: 'supermarket' | 'drugstore' | 'shopping'; address: string; url: string; notes: { zh:string; en:string; de:string } };

// Location and link review: 2026-09-21. ALDI remains a branch locator; see docs/data-review-2026-09-21.md.
export const lifePlaces: LifePlace[] = [
  { id:'dm-bahnhofstrasse', name:'dm · Bahnhofstraße', category:'drugstore', address:'Bahnhofstraße 71–73, 66111 Saarbrücken', url:'https://www.dm.de/store/d4db/saarbruecken', notes:{"zh": "周一至周六 09:00–20:00，周日休息；日化、美妆与生活用品。", "en": "Mon–Sat 09:00–20:00; closed Sunday. Beauty and everyday essentials.", "de": "Mo–Sa 9–20 Uhr, sonntags geschlossen. Drogerie und Alltagsprodukte."} },
  { id:'edeka-mainzer', name:'EDEKA Lonsdorfer', category:'supermarket', address:'Mainzer Straße 64, 66121 Saarbrücken', url:"https://www.edeka.de/maerkte/048152/", notes:{"zh": "周一至周六 07:00–20:00，周日休息；官网可查本周促销。10 月 3 日休息。", "en": "Mon–Sat 07:00–20:00; closed Sunday and 3 October. See this branch’s weekly offers online.", "de": "Mo–Sa 7–20 Uhr; sonntags und am 3. Oktober geschlossen. Wochenangebote auf der Filialseite."} },
  { id:'rewe-europa', name:'REWE · Europa-Galerie', category:'supermarket', address:'Trierer Straße 1, 66111 Saarbrücken', url:"https://www.europagalerie.de/center-info/offnungszeiten/", notes:{"zh": "购物中心官网列出 REWE 周一至周六 08:00–20:00；营业时间与中心其他店铺不同。", "en": "The centre lists REWE hours as Mon–Sat 08:00–20:00, earlier than most shops in the mall.", "de": "Laut Center öffnet REWE Mo–Sa 8–20 Uhr, früher als die meisten anderen Geschäfte."} },
  { id:'aldi-saarbruecken', name:'ALDI SÜD · Saarbrücken', category:'supermarket', address:'Saarbrücken · Filialfinder', url:'https://www.aldi-sued.de/filialen/de-de/Search?Mode=None&SingleSlotGeo=95469', notes:{zh:'通过官网查询附近分店；分享好物时请注明具体分店与购买日期。',en:'Find a branch in the official locator. Include the branch and purchase date with your find.',de:'Filiale im offiziellen Filialfinder wählen. Bitte Filiale und Kaufdatum beim Fund angeben.'} },
  { id:'kaufland-saarbasar', name:'Kaufland · Saarbasar', category:'supermarket', address:'Breslauer Straße 1 A, 66121 Saarbrücken', url:'https://filiale.kaufland.de/service/filiale/saarbruecken-5043.html', notes:{"zh": "周一至周六 07:00–20:00，周日休息；官网可查看 Saarbasar 本店每周促销。", "en": "Mon–Sat 07:00–20:00; closed Sunday. The branch page lists weekly Saarbasar offers.", "de": "Mo–Sa 7–20 Uhr, sonntags geschlossen. Wochenangebote für den Saarbasar auf der Filialseite."} },
  { id:'europa-galerie', name:'Europa-Galerie', category:'shopping', address:'Trierer Straße 1, 66111 Saarbrücken', url:"https://www.europagalerie.de/center-info/offnungszeiten/", notes:{"zh": "商店通常周一至周六 09:30–20:00；官网公布 10 月 4 日周日购物 11:00–18:00，具体店铺请另行确认。", "en": "Shops usually open Mon–Sat 09:30–20:00. The centre announces Sunday shopping on 4 October, 11:00–18:00; check individual shops.", "de": "Geschäfte regulär Mo–Sa 9:30–20 Uhr. Das Center kündigt für den 4. Oktober einen verkaufsoffenen Sonntag von 11–18 Uhr an; einzelne Läden bitte prüfen."} },
  { id:'saarbasar', name:'Saarbasar', category:'shopping', address:'Breslauer Straße 1 A, 66121 Saarbrücken', url:'https://www.saarbasar.de/anfahrt/', notes:{zh:'购物中心与日常采购；分享服饰、家居和生活好物。',en:'Shopping and everyday supplies. Share clothing, homeware and everyday finds.',de:'Shopping und täglicher Einkauf: Teile Kleidung, Haushaltswaren und Alltagsfunde.'} },
  { id:'bahnhofstrasse-shopping', name:'Bahnhofstraße · Shopping', category:'shopping', address:'Bahnhofstraße, 66111 Saarbrücken', url:'https://einkaufen.saarbruecken.de/shopping/shopping_quartiere/city_quartier_bahnhofstrasse', notes:{zh:'市中心商业街；分享沿街小店、礼物和购物发现。',en:'Central shopping street. Share shops, gifts and discoveries along the way.',de:'Einkaufsstraße im Zentrum: Teile Geschäfte, Geschenke und Entdeckungen.'} },
];
export const lifePlaceKey = (place: LifePlace) => `life:${place.id}`;
