export type LifePlace = { id: string; name: string; category: 'supermarket' | 'drugstore' | 'shopping'; address: string; url: string; notes: { zh:string; en:string; de:string } };

// Store locations checked against the linked official directories on 2026-09-09.
export const lifePlaces: LifePlace[] = [
  { id:'dm-bahnhofstrasse', name:'dm · Bahnhofstraße', category:'drugstore', address:'Bahnhofstraße 71–73, 66111 Saarbrücken', url:'https://www.dm.de/store/d4db/saarbruecken', notes:{zh:'日化、美妆与生活用品；分享你的护肤、清洁或零食发现。',en:'Beauty and everyday essentials. Share skincare, household or snack finds.',de:'Drogerie und Alltagsprodukte: Teile Kosmetik-, Haushalts- oder Snack-Fundstücke.'} },
  { id:'edeka-mainzer', name:'EDEKA Lonsdorfer', category:'supermarket', address:'Mainzer Straße 64, 66121 Saarbrücken', url:'https://www.edeka.de/markt-id/10002020/prospekt.jsp', notes:{zh:'日常食材与生鲜采购；分享喜欢的食材和货架发现。',en:'Groceries and fresh food. Share ingredients and shelf discoveries.',de:'Lebensmittel und Frischeprodukte: Teile Zutaten und Entdeckungen aus dem Regal.'} },
  { id:'rewe-europa', name:'REWE · Europa-Galerie', category:'supermarket', address:'Trierer Straße 1, 66111 Saarbrücken', url:'https://www.rewe.de/marktsuche/saarbruecken/', notes:{zh:'市中心购物时顺路补货；分享饮料、零食和日常食材。',en:'Groceries while shopping in the city centre. Share drinks, snacks and staples.',de:'Einkaufen in der Innenstadt: Teile Getränke, Snacks und Lebensmittel.'} },
  { id:'aldi-saarbruecken', name:'ALDI SÜD · Saarbrücken', category:'supermarket', address:'Saarbrücken · Filialfinder', url:'https://www.aldi-sued.de/filialen/de-de/Search?Mode=None&SingleSlotGeo=95469', notes:{zh:'通过官网查询附近分店；分享好物时请注明具体分店与购买日期。',en:'Find a branch in the official locator. Include the branch and purchase date with your find.',de:'Filiale im offiziellen Filialfinder wählen. Bitte Filiale und Kaufdatum beim Fund angeben.'} },
  { id:'kaufland-saarbasar', name:'Kaufland · Saarbasar', category:'supermarket', address:'Breslauer Straße 1 A, 66121 Saarbrücken', url:'https://filiale.kaufland.de/service/filiale/saarbruecken-5043.html', notes:{zh:'大型超市，官网可查本店促销；分享囤货清单和新发现。',en:'Large supermarket with branch offers online. Share stock-up favourites and discoveries.',de:'Großer Supermarkt mit Filialangeboten online. Teile Vorratslieblinge und neue Entdeckungen.'} },
  { id:'europa-galerie', name:'Europa-Galerie', category:'shopping', address:'Trierer Straße 1, 66111 Saarbrücken', url:'https://www.europagalerie.de/centermanagement/', notes:{zh:'市中心购物中心；晒好物时注明是哪家店买到的。',en:'City-centre shopping mall. Mention the shop where you found your purchase.',de:'Einkaufszentrum in der Innenstadt. Nenne beim Teilen auch das Geschäft.'} },
  { id:'saarbasar', name:'Saarbasar', category:'shopping', address:'Breslauer Straße 1 A, 66121 Saarbrücken', url:'https://www.saarbasar.de/anfahrt/', notes:{zh:'购物中心与日常采购；分享服饰、家居和生活好物。',en:'Shopping and everyday supplies. Share clothing, homeware and everyday finds.',de:'Shopping und täglicher Einkauf: Teile Kleidung, Haushaltswaren und Alltagsfunde.'} },
  { id:'bahnhofstrasse-shopping', name:'Bahnhofstraße · Shopping', category:'shopping', address:'Bahnhofstraße, 66111 Saarbrücken', url:'https://einkaufen.saarbruecken.de/shopping/shopping_quartiere/city_quartier_bahnhofstrasse', notes:{zh:'市中心商业街；分享沿街小店、礼物和购物发现。',en:'Central shopping street. Share shops, gifts and discoveries along the way.',de:'Einkaufsstraße im Zentrum: Teile Geschäfte, Geschenke und Entdeckungen.'} },
];
export const lifePlaceKey = (place: LifePlace) => `life:${place.id}`;
